config/routes.rb
Rails.application.routes.draw do

#  get 'users/show'
#  root 'homes#top'
#  devise_for :users
#  get 'books/new'
#  post 'books' => 'book#create'
#  resources :users, only: [:index, :show]
#  resources :books, only: [:new, :create, :index, :show, :destroy]



#  get 'users/show'
  devise_for :users
  root 'homes#top'

#  get 'books/new'
#  post 'books' => 'book#create'

  resources :users, only: [:index, :show]
  resources :books, only: [:new, :create, :index, :show, :destroy]



# これは、めしてろ
#  root 'homes#top'
#  devise_for :users
#  resources :post_images, only: [:new, :create, :index, :show, :destroy]
#  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
#    resource :favorites, only: [:create, :destroy]
#    resources :post_comments, only: [:create, :destroy]
#  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  #belongs_to :book
  # attachment :image # ここを追加（_idは含めません）

  validates :title, presence: true

#  def favorited_by?(user)
#    favorites.where(user_id: user.id).exists?
#  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    books_path
#    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:introduction])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_image_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

#  def create
#    @book = Book.new(params[:id])
#    @book.save
#    redirect_to books_path
#  end
  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end


  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.find(params[:id])
  end

  # 投稿データのストロングパラメータ
  private

  def books_path
    params.require(:user).permit(:name, :introduction, :profile_image_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h2>HTMLファイル：views/books/index.html.erb</h2>


<% @books.each do |book| %>
<div>
  <p>ブック名：<%= book.title %></p>
  <p>説明：<%= book.body %></p>
</div>

<% end %>

app/views/books/new.html.erb
<h2>HTMLファイル：views/books/new.html.erb</h2>
<h1>画像投稿フォーム</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>ブック名</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<h2>HTMLファイル：views/books/show.html.erb</h2>

app/views/homes/top.html.erb
<h1>トップページ！！！</h1>
<h2>HTMLファイル：views/homes/top.html.erb</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<h2>HTMLファイル：views/layouts/application.html.erb</h2>

    <% if user_signed_in? %>
      <li>
        <%= link_to 'ブック', new_book_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<h2>HTMLファイル：views/users/index.html.erb</h2>
<div>
  <%= link_to user_path(@user.id) do %>
　  <%= attachment_image_tag user, :image %>
  <% end %>
  <p>ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>名前：<%= user.name %></p>
  <p>自己紹介文：<%= user.introduction %></p>
</div>

app/views/users/new.html.erb
<h2>HTMLファイル：views/users/new.html.erb</h2>
<h1>ユーザ画面</h1>
<%= form_with model: @user, local:true do |f| %>
  <h4>ユーザ名</h4>
  <%= f.text_field :name %>
  <h4>自己紹介</h4>
  <%= f.text_area :introduction %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/show.html.erb
<h2>HTMLファイル：views/users/show.html.erb</h2>


<div>
  <h3><%= @user.name %></h3>
  <%= image_tag('sample-author1.jpg') %>
</div>